# Generated by Django 5.1.5 on 2025-02-02 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(blank=True, max_length=75, null=True)),
                ('gradeSection', models.CharField(blank=True, max_length=40, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('dateSubmitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('damagedProperty', models.CharField(blank=True, choices=[('chair', 'Chair'), ('table', 'Table'), ('electricfan', 'Electric Fan'), ('outlet', 'Outlet'), ('television', 'Television'), ('whiteboard', 'Whiteboard'), ('tiles', 'Tiles'), ('window', 'Window'), ('other', 'Other')], default=None, max_length=5000, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classnotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
